### ISSUE TITLE
qBittorrent Web 用户界面无法登陆，“无效的用户名或密码。”

### ISSUE THREAD

**Issue by smart-z** [gshang2017/docker#10]
- 您好，感谢您开发这样的工具。
- 我先是手动docker的方式安装，手动配置，结果配置完成启动后，打开页面是空白什么都没有。发现这个方法不成功就试了命令行的方法。
- mac终端root群晖用命令行的方法安装可以启动，可以打开页面。输入用户名admin密码adminadmin无法登陆，我注意到您的文档写了个“adminadmin)，还是一样”提示“无效的用户名或密码。”
- 您看我这种情况有办法处理么？
- 
- 令人震惊的事情发生了，现在出现了“身份认证失败次数过多，您的 IP 地址已被封禁。”，自己把自己给杀了

**Comment by smart-z** [comment]
真是囧，原来是chrome的问题，重新折腾后，可以正常登陆，问题关闭。囧

**Comment by johnita-biubiu** [comment]
> 真是囧，原来是chrome的问题，重新折腾后，可以正常登陆，问题关闭。囧
我也是这个问题，请问最后怎么解决的？

**Comment by smart-z** [comment]
> > 真是囧，原来是chrome的问题，重新折腾后，可以正常登陆，问题关闭。囧
> > 我也是这个问题，请问最后怎么解决的？

先换其它浏览器，能登陆了再说。
禁止本页的chrome扩展和脚本

**Comment by xxy9468615** [comment]
禁止了一样无法登入。。
