### ISSUE TITLE
求问 johngong/tt-rss 的 Docker 能否支持一下非标准端口订阅呢？

### ISSUE THREAD

**Issue by akimolll** [gshang2017/docker#103]
一直在使用johngong/tt-rss，但是现在遇到一个问题。

因为在群晖里搭建的RSSHub自带1200端口，比如：192.168.1.111:1200，而RSSHub生成的订阅地址就是类似这样的：https://192.168.1.111:1200/github/comments/gshang2017/docker/issues/new 

而现在新版本的TTRSS已经不支持80 443以外的订阅端口了。可是家里的 80 443都被封了，群晖里不得不使用端口订阅，这就比较尴尬。

想问下，有什么办法可以通过在Docker里添加环境变量之类的方法，来解除这个非标准端口不能订阅的限制呢？

感谢。

**Comment by gshang2017** [comment]
新增加了环境变量 TTRSS_ALLOW_PORTS ，docker pull johngong/tt-rss:latest ，设置TTRSS_ALLOW_PORTS=1200，新版升级了数据库需要先用旧版备份数据库。

**Comment by akimolll** [comment]
> 新增加了环境变量 TTRSS_ALLOW_PORTS ，docker pull johngong/tt-rss:latest ，设置TTRSS_ALLOW_PORTS=1200，新版升级了数据库需要先用旧版备份数据库。

谢谢大佬的Docker，我直接备份了一下.xml，完全重装了，现在配合RSSHub完美运行，感谢。😊
