### ISSUE TITLE
图书封面上传会颜色变很深，是啥原因？

### ISSUE THREAD

**Issue by flyxj** [gshang2017/docker#104]
0.6.16 这一版，autoaddbooks添加的图书封面是正常的，但是在编辑图书时本地上传或者在线获取的封面颜色会变色加深，不知道大家有没有遇到。请问这个哪里修正？

上传后变色封面和原封面对比：

![图像 001](https://user-images.githubusercontent.com/1892385/155684003-17ffe848-0481-43d4-8c05-de1104ae5bdb.png)

**Comment by tecsar9000** [comment]
0.6.18 也有这个情况，图片打开是正常的，就是上传了以后看起来特别深

**Comment by flyxj** [comment]
> 

我现在有时就不更新封面了，在抓取豆瓣信息后，把封面那一栏去掉。我去 calibre-web 那边问，也没答复。

**Comment by album-GitHub** [comment]
同样有这个问题，看起来像是图片过大时压缩的问题

**Comment by tecsar9000** [comment]
我怀疑是阿尔法通道的问题，是不是上传进去的图片没了alpha

**Comment by album-GitHub** [comment]
> 我怀疑是阿尔法通道的问题，是不是上传进去的图片没了alpha

jpg格式也会这样，但jpg没有透明通道

**Comment by gshang2017** [comment]
#180
