### ISSUE TITLE
请问qbit的高级设置和桌面版本的区别是否生效？

### ISSUE THREAD

**Issue by ayd13swb** [gshang2017/docker#105]
https://s4.ax1x.com/2022/03/03/bYP5gf.png

https://s4.ax1x.com/2022/03/03/bYPIv8.png

主要就是缓存这部分的设置，Docker版本有这个选项，但是显示需要lib小于2.0版本，然后我看现在用的已经是大于2.0的版本了，而且我对比了一下桌面版本，已经没有这些选项了。

那么这些选项是否还生效？

**Comment by gshang2017** [comment]
应该不会生效。libtorrent 2.0的缓存由操作系统处理。

**Comment by ayd13swb** [comment]
> 应该不会生效。libtorrent 2.0的缓存由操作系统处理。

那就好，那我就默认的-1了。

不过劳驾请问下，为什么Docker版本的还有这些设置？Docker版本和win还有mac版本不太一样么？因为不止是您的版本有这个选项，我原来用的linuxserver的那个版本也是这样，所以一直挺好奇的

**Comment by gshang2017** [comment]
docker版用的是qbittorrent-nox，通过WebUI访问。并不是完整的桌面程序。两者UI是不同的。目前还有这些设置应该是处于过度阶段。

**Comment by ayd13swb** [comment]
> docker版用的是qbittorrent-nox，通过WebUI访问。并不是完整的桌面程序。两者UI是不同的。目前还有这些设置应该是处于过度阶段。

非常感谢您的解惑。
