### ISSUE TITLE
关于元数据获取导致Web卡死的情况

### ISSUE THREAD

**Issue by HalcyonAzure** [gshang2017/docker#106]
前置条件：拉取了最新的`Calibre-Web`的镜像，并且搭建好了`simple-boot-douban-api`开放对应端口

出现问题：在试图获取元数据的时候`Calibre-Web`会出现卡死的情况，需要重启容器才能恢复，并且无法查询到对应元数据

目前的解决方案：

1. 豆瓣的API无法使用：

根据`fugary`发布的新api：[calibre-web-douban-api](https://github.com/fugary/calibre-web-douban-api)内的帮助文档，将`NewDouban.py`相对应的内容放于`metadata_provider`下。同时从`fugary`的[博客](https://fugary.com/?p=238)当中了解到可能的原因：

> ​ 豆瓣api很早以前就已经不开放给个人用户使用了，目前的豆瓣API provider是自己开发的，使用python从豆瓣网站上抓取网页并解析成对应格式数据的方式实现。
以前开发了一个Java版本（https://github.com/fugary/simple-boot-douban-api）
豆瓣api镜像发布到Docker仓库可以启动后供javascript调用，但是新版calibre-web不再使用javascript调用外部服务的方式获取元数据，因此根据calibre-web的metadata_provider规范开发了python版本并开源到Github上

2. 网页出现卡死的问题：

禁用`metadata_provider`下谷歌等其他第三方接口（直接删除/重命名对应py文件）后，成功使用新的豆瓣API进行元数据的修改，其中可能的原因：

> 最近有不少网友说查询的时候卡死，其实是因为内置的google和scholar等其他元数据provider引起的。要解决这个问题可以以下方案：
> 1. 考虑配梯子等访问外网，并去掉google等元数据选项。
> 2. 直接通过挂接覆盖原来的元数据文件夹，不过这样就只有豆瓣搜索了。

**Comment by dandelions** [comment]
直接把其他元数据选项备份掉就好了

**Comment by 34292885** [comment]
Encountered the same problem

**Comment by 34292885** [comment]
> 直接把其他元数据选项备份掉就好了

備份掉是什麼意思？
