### ISSUE TITLE
更新最新版qbitee后 任务信息页无法加载

### ISSUE THREAD

**Issue by AlfredQingyao** [gshang2017/docker#108]
![image](https://user-images.githubusercontent.com/25794476/158066708-fca125a3-d336-4e8b-b51f-953a01b2427d.png)
尝试过重启docker、CTRL F5依然无信息

**Comment by gshang2017** [comment]
不知道下的什么架构，我这里测试是正常的，有人说是cpu性能不好需要等到trackers全部连接完毕才能正常。或者你可以去下载官方编译的映射到容器里(/usr/local/bin/qbittorrentee-nox)试试。  https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.4.1.10
