### ISSUE TITLE
qbittorrent QB_EE_BIN参数无效

### ISSUE THREAD

**Issue by BlueSkyClouds** [gshang2017/docker#109]
QB_EE_BIN 已设置成true 依旧无法使用qBittorrent-EE
![1](https://user-images.githubusercontent.com/39831773/158069164-38aeb89e-6c5c-4bc2-b2f0-82b854511ecc.png)
![2](https://user-images.githubusercontent.com/39831773/158069167-b0a77a79-87a2-4519-b9ed-1584c06e9ef8.png)

**Comment by gshang2017** [comment]
只有最新4.4.1-4.4.1.10及latest的才可以使用，需要旧版可以下载qee-latest。详见： https://github.com/gshang2017/docker/blob/master/qBittorrent/README.md

**Comment by muihiuwev** [comment]
> 只有最新4.4.1-4.4.1.10及latest的才可以使用，需要旧版可以下载qee-latest。详见： https://github.com/gshang2017/docker/blob/master/qBittorrent/README.md

latest 拉取的仍是 4.3.9 版本不是最新的4.4.2，QB_EE_BIN 不生效。

**Comment by gshang2017** [comment]
https://hub.docker.com/r/johngong/qbittorrent/tags

**Comment by muihiuwev** [comment]
所以 latest 不是最新的？要指定 tag？

**Comment by gshang2017** [comment]
latest是最新的，可能你的镜像源有问题。建议你试下tag，看行不行。

**Comment by muihiuwev** [comment]
镜像源的问题，我用了阿里云的。[官方说明](https://help.aliyun.com/document_detail/60750.html?spm=5176.8351553.help.dexternal.3ea91991L9n0I8&scm=20140722.S_help%40%40%E6%96%87%E6%A1%A3%40%4060750.S_0%2Bos.ID_60750-RL_%E9%95%9C%E5%83%8F%E5%8A%A0%E9%80%9F-LOC_consoleUNDhelp-OR_ser-V_2-P0_0#:~:text=%E8%AF%B4%E6%98%8E%20%E7%9B%AE%E5%89%8D%E7%94%B1%E4%BA%8EDocker%20Hub%E9%99%90%E5%88%B6%EF%BC%8C%E5%AF%BC%E8%87%B4%E4%BD%BF%E7%94%A8%E9%95%9C%E5%83%8F%E5%8A%A0%E9%80%9F%E5%99%A8%E5%90%8E%E6%97%A0%E6%B3%95%E8%8E%B7%E5%8F%96%E6%9C%80%E6%96%B0%E5%AE%98%E6%96%B9%E9%95%9C%E5%83%8F%E3%80%82%E8%AF%B7%E6%9A%82%E6%97%B6%E5%8E%BB%E6%8E%89%E5%8A%A0%E9%80%9F%E5%99%A8%E9%85%8D%E7%BD%AE%EF%BC%8C%E7%9B%B4%E6%8E%A5%E8%BF%9E%E6%8E%A5Docker%20Hub%E8%8E%B7%E5%8F%96%E3%80%82)

**Comment by BlueSkyClouds** [comment]
我也是阿里云的
