### ISSUE TITLE
qbittorrent 普通版本4.20 种子的详情无法显示 没有内容

### ISSUE THREAD

**Issue by gzxiexl** [gshang2017/docker#11]
点击每个种子 详情 Tracker 等信息均无内容 重置了都没有用

**Comment by gshang2017** [comment]
没发现这种状况。

**Comment by yufeiyang2008** [comment]
群晖docker默认配置，打不开webui控制页，什么问题啊

**Comment by binsee** [comment]
qBittorrent v4.2.1.10 Web UI (Enhnaced Edition) (64-bit) 同样出现此问题

**测试不同浏览器会有差异**
操作系统： Win10 1909

- Chrome 79.0.3945.88 
  - 详情中不显示数据
  - Tracker、内容 分页中空白
  - 开发者工具中报错信息如下:
```
   Uncaught ReferenceError: ContextMenu is not defined
    at prop-trackers.js:137
(anonymous) @ prop-trackers.js:137
```

- Microsoft Edge 44.18362.449.0

一切正常

----

根据和PC版 qBittorrent v4.2.1.10 (Enhnaced Edition) (64-bit) 的进行对比，PC版本的Web UI在chrome和Edge中显示都是正常的。

通过对比，发现`scripts/prop-*.js`这几个js内容不同，主要表现在不同浏览器中兼容性问题。
通过测试，发现似乎会受 `User-Agent`影响，返回不同版本的js脚本，如在chrome中返回的
- prop-general.js
- prop-trackers.js
- prop-webseeds.js
- prop-files.js

和通过 `curl http://bt/scripts/prop-files.js` 返回的内容不同。

而错误的js版本中，如
-  prop-general.js 中调用了`friendlyDuration()`和`friendlyUnit()`，而其命名空间应在`window.qBittorrent.Misc` 下，缺少了前缀，导致在`window`空间下找不到。由于是在`'text'.replace()`中调用，因此没有明确的报错
-  prop-general.js 中调用了`new ContextMenu()`，而其命名空间应在`window.qBittorrent.ContextMenu` 下，缺少了前缀，导致在`window`空间下找不到。由于是new了一个不存在的Class，因此报错。

-----

总结，根本原因在于编译入了错误的js脚本，理论来说更新js脚本即可。
