### ISSUE TITLE
群晖码头工人配置，打不开webui控制页，什么问题啊

### ISSUE THREAD

**Issue by yufeiyang2008** [gshang2017/docker#12]
群晖docker下，qbittorrent默认配置，卷也设置好了，正常启动，日志显示正常，可访问不了webui

**Comment by gshang2017** [comment]
环境变量(-e WEBUIPORT=8989)与web访问端口(-p 8989:8989)三个数值需一致。

**Comment by yufeiyang2008** [comment]
是一致的，还有其他问题吗

**Comment by yufeiyang2008** [comment]
问题解决了，我把端口改成8866，可用了，谢谢你的回复
