### ISSUE TITLE
johngong/tt-rss，请教大佬，要如何安装插件。

### ISSUE THREAD

**Issue by i-iooi-i** [gshang2017/docker#123]
请教大佬，我已经把plugins.local文件夹在群晖里映射出来了，现在想安装一些ttrss-sendtokindle之类的插件试用一下，但是把这些插件解压到plugins.local目录，重启Docker没啥反应。小白，特来求教。😢😢😢

**Comment by gshang2017** [comment]
安装插件

复制到插件文件夹plugins.local，然后在设置面板中激活它。插件文件夹名称应与定义的插件类名称相对应(plugin)/init.php，即 Af_ExamplePlugin应复制到plugins.local/af_exampleplugin。


如果安装了没用，可能是插件不支持较新的ttrss版本。

**Comment by i-iooi-i** [comment]
> 安装插件
> 
> 复制到插件文件夹plugins.local，然后在设置面板中激活它。插件文件夹名称应与定义的插件类名称相对应(plugin)/init.php，即 Af_ExamplePlugin应复制到plugins.local/af_exampleplugin。
> 
> 如果安装了没用，可能是插件不支持较新的ttrss版本。

感谢大佬指点，看了一眼那个[sendtokindle](https://github.com/usr42/ttrss-sendtokindle)插件，是停留在5年前。
在新版本的TTRSS是整不活了，就不折腾了。🤣🤣🤣
