### ISSUE TITLE
请问一下ttrss能不能设置代理？如果能设置的话，该如何设置？

### ISSUE THREAD

**Issue by ihaihe** [gshang2017/docker#125]

**Comment by gshang2017** [comment]
https://github.com/hacklu/options_per_feed/tree/bug_fix

**Comment by 0rt** [comment]
nice。刚好想上来问一个ssl验证的问题的，这个看来能一并解决。先试试

**Comment by 0rt** [comment]
> https://github.com/hacklu/options_per_feed/tree/bug_fix

报告一下。完美。我一个原来SSL证书问题不能打开的的订阅，用了这个后就正常了（我折腾了两天用huginn忽略ssl验证中转一次，没有搞成功）。而且有referer，cookie和ua、代理这些设置，很有用，建议集成。不然对萌新来说不太好安装。

或者你可以置顶一个第三方安装插件安装教程。我才了一些坑才完成了。@ihaihe 你可以参考一下
1. 文件夹放在docker里的 /usr/local/tt-rss/app/plugins 目录下，插件文件夹名字必须和init.php里面定义的一样，比如这个插件是options_per_feed，大小写敏感，搞好以后进TTrss设置就能看到，不用重启。
2. 给容器传文件，可以用sudo docker ps获得容器id后，用sudo docker -it 容器id /bin/bash 进入容器命令行用vi新建，也可以SSH连到容器里面直接传

**Comment by ihaihe** [comment]
@[gshang2017](https://github.com/gshang2017)
@[0rt](https://github.com/0rt)
谢谢两位，按照方法已经解决！
