### ISSUE TITLE
刚刚装上，经常启动不了，要多次重新启动才偶尔成功，失败的时候日志都是这样的：

### ISSUE THREAD

**Issue by 0rt** [gshang2017/docker#126]
05:59:24 Already up to date.
06:05:07[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
06:05:07[s6-init] ensuring user provided files have correct perms...exited 0.
06:05:07[fix-attrs.d] applying ownership & permissions fixes...stdout
06:05:07[fix-attrs.d] done.
06:05:07[cont-init.d] executing container initialization scripts...
06:05:07[cont-init.d] tt-rss.sh: executing... 
06:05:08tt-rss更新任务已存在。

没有改任何设置，直接拉下来启动就这样了

**Comment by gshang2017** [comment]
可能是你的网络访问ttrss服务器太慢，卡在更新上了。试下关掉自动更新TTRSS_UPDATE_AUTO=false。

**Comment by 0rt** [comment]
> 可能是你的网络访问ttrss服务器太慢，卡在更新上了。试下关掉自动更新TTRSS_UPDATE_AUTO=false。

谢谢。现在运行起来了，我先用几天，下次需要重新启动的时候测试反馈结果

**Comment by 0rt** [comment]
确认自动更新关闭后正常。这边网络问题。
