### ISSUE TITLE
zhparser 配置求助

### ISSUE THREAD

**Issue by 0rt** [gshang2017/docker#128]
折腾主要是想弄这个中文搜索过滤。但遇到问题，搜索后尝试一番无果只能求助。除了端口和ip以外，所有都是默认配置。
![image](https://user-images.githubusercontent.com/822795/174563224-7edfb7d8-5a1b-4edf-be77-926b5c6fb220.png)
zhparser：
psql -U ttrss -d ttrss -a -f /docker-entrypoint-initdb.d/install_extension.sql

SSH登录到群晖，输入上面命令
第一个问题：提示
psql: FATAL:  Peer authentication failed for user "ttrss"

百度一番，好像解决了，
sudo vi /etc/postgresql/pg_hba.conf
里面把认证方式从peer改成md5，[来源](https://www.freesion.com/article/5977224905/)
![image](https://user-images.githubusercontent.com/822795/174563462-71d5ad9d-ed21-4ed6-8ad1-780332cd63f9.png)
sudo synoservice --restart pgsql 

重复开始的命令
psql -U ttrss -d ttrss -a -f /docker-entrypoint-initdb.d/install_extension.sql
不一样了，提示输入密码
Password for user ttrss:
psql: FATAL:  password authentication failed for user "ttrss"
问题是输入密码ttrss后说密码错误，彻底卡住了。求指导
![image](https://user-images.githubusercontent.com/822795/174563665-16beed16-f3ab-4084-9ab8-1cbeda54b8ab.png)

**Comment by gshang2017** [comment]
命令是用在容器内的，是给旧版升级用的，新版直接设置就行(偏好设置-信息源-默认语言-Chinese_simplified)。

**Comment by 0rt** [comment]
明白了。你真是个热心肠！确认有效
