### ISSUE TITLE
qBittorrent原版是否也能增加一个arm64版？

### ISSUE THREAD

**Issue by NagaseKouichi** [gshang2017/docker#13]
现在arm64版只有qee版，没有原版集成Trackers自动更新的，qee版在MT站用不了。是否能出一个arm64的原版集成Trackers自动更新的版本呢？

一直用大佬的版本，小巧，功能强大，非常喜欢。

**Comment by gshang2017** [comment]
johngong/qbittorrent:4.2.1_arm64v8

**Comment by NagaseKouichi** [comment]
已完美部署，非常感谢大神！
