### ISSUE TITLE
Calibre Web 没有在线转换电子书选项

### ISSUE THREAD

**Issue by bao3** [gshang2017/docker#130]
`johngong/calibre-web` 的  latest ,安装好各功能正常，但是发现没有在线转换电子书格式的选项（`/opt/calibre/ebook-convert` 正常)
检查了一下设置，没找到。求教有什么办法吗？

**Comment by gshang2017** [comment]
编辑元数据-转换书籍格式

**Comment by bao3** [comment]
> 编辑元数据-转换书籍格式

找到了.

Closed
