### ISSUE TITLE
树莓派启动calibre-web相关问题

### ISSUE THREAD

**Issue by TyrantLucifer** [gshang2017/docker#139]
我在树莓派3B+上部署了calibre-web，由于将三个目录设置成为了我树莓派挂载的smb共享文件夹下，镜像启动的过程中一直报database is locked，请问有什么办法解决吗？树莓派自带的存储较小，实际上想把数据放在nas上存储，但目前看来docker内部容器在去操作sqllite数据库的时候遇到了文件权限相关的问题，相关数据库文件不能放在nas存储上，请问作者有遇到过这种情况吗？

![image](https://user-images.githubusercontent.com/51053924/187877061-a5afad03-399d-46aa-98b0-4337445734f0.png)

启动命令

```shell

 docker create  \
    --name=calibre-web  \
    --privileged=true \
    -p 8083:8083  \
    -e UID=1000  \
    -e GID=1000  \
    -v /home/pi/calibre-web/config:/config  \
    -v /home/pi/calibre-web/library:/library  \
    -v /home/pi/calibre-web/autoaddbooks:/autoaddbooks  \
    --restart unless-stopped  \
    johngong/calibre-web:arm64v8-latest

```

其中calibre-web是nas挂载目录的软链接，实际在测试过程中，如果将三个目录都设置成为树莓派本机目录问题就没有，由于对docker没有那么精通所以想要请教一下这个问题是什么问题？对了，我nas挂载的目录是777权限，文件所属UID和GID也是1000

![image](https://user-images.githubusercontent.com/51053924/187877538-6cf2e77f-6f7d-44e0-9814-f431522d185a.png)

![image](https://user-images.githubusercontent.com/51053924/187877592-08035c47-5985-4389-b3e4-ae27c37f37be.png)

**Comment by gshang2017** [comment]
挂载smb时添加nobrl参数试下。

**Comment by TyrantLucifer** [comment]
真的牛我的哥，我拜服，这个参数真的能让sqlite在共享存储中用了！感谢！

**Comment by TyrantLucifer** [comment]
还有一个问题是编辑书籍元数据会卡死，这个作者遇到过吗？

**Comment by gshang2017** [comment]
如果是获取书籍元数据就卡死，可能是开启了Google元数据搜索的原因,你可以更改环境变量试下:
DISABLE_GOOGLE_SEARCH=true
DISABLE_SCHOLAR_SEARCH=true

**Comment by TyrantLucifer** [comment]
看到了其他的issue，得到了解决方案，谢谢作者一直维护这么好用的镜像！
