### ISSUE TITLE
您好，请教个问题。

### ISSUE THREAD

**Issue by smart-z** [gshang2017/docker#14]
您好，我不是程序员对技术不太懂。因为求助无门，我的环境也不允许自己测试，所以不得不来请教您一下。

1. qee增强版是否可以latest自动更新？
2. 我之前装了4.19，现在删了重新装4.20，是否会损失目前的下载进度和文件？

感谢

**Comment by gshang2017** [comment]
1.latest标签的是原版qbittorrent。
2.不用PT,BT只要/config和/Downloads文件夹是映射到容器外的,就不会损失目前的下载进度和文件。但4.20的密码会重置为原始密码。

**Comment by smart-z** [comment]
> 1.latest标签的是原版qbittorrent。
> 2.不用PT,BT只要/config和/Downloads文件夹是映射到容器外的,就不会损失目前的下载进度和文件。但4.20的密码会重置为原始密码。

好的，感谢您的帮助
