### ISSUE TITLE
baidunetdisk:4.12.5 使用novnc后，浏览器有无法关闭的错误弹窗

### ISSUE THREAD

**Issue by liwufan** [gshang2017/docker#141]
https://github.com/gshang2017/docker/commit/04ed1ba5a8d7258d22ef2f7dbb7163e179647860 之后我用火狐打开网页会弹出无法关闭的错误，影响鼠标点击选择操作。
<img width="1097" alt="ss" src="https://user-images.githubusercontent.com/32187698/188824447-ff489ace-0dee-4d51-9c1c-948a7a06f7e1.png">

**Comment by gshang2017** [comment]
已修复，docker pull johngong/baidunetdisk:latest
