### ISSUE TITLE
0.6.19 DOUBANIP这个环境变量后边填什么参数才能正确启用豆瓣刮削？

### ISSUE THREAD

**Issue by alasion** [gshang2017/docker#165]
DOUBANIP 这个变量后面应该填什么参数才能正确启用豆瓣刮削？
我试了默认留空，刮削器里面不显示豆瓣刮削。
填写true，刮削器显示 搜索错误！!加载中...
注：已禁用google、scholar搜索。

**Comment by alasion** [comment]
> 新版不支持DOUBANIP，0.6.19的已经失效了，你可以手动更新下： https://raw.githubusercontent.com/janeczku/calibre-web/73567db4fb01b934604f3d17f7d025d9b4e61f6f/cps/metadata_provider/douban.py 位置在容器里/usr/local/calibre-web/app/cps/metadata_provider

我在卷设置中把这个文件夹映射出来了，您提供的这个文件我放到了映射文件夹中，重启后问题依旧。
是这个文件夹不支持映射吗？

**Comment by gshang2017** [comment]
可以映射。

**Comment by gshang2017** [comment]
路径没问题，你可以进容器内部看一下你映射的是不是正确的。一个简单的方法是用管理权限-基本配置-扩展程序-路径 去找找那个文件夹。

**Comment by alasion** [comment]
搞定了，但是过程很玄学，先安装0.6.18版本，路径按照作者上面提供的映射没问题，然后从calibre-web里更新到0.6.19，这样0.6.19的路径映射就能继承上一个版本，可以正常映射，然后用[calibre-web-douban-api](https://github.com/fugary/calibre-web-douban-api)这个newdouban.py就可以正常使用刮削了。
