### ISSUE TITLE
 baidunetdisk 消息页灰屏

### ISSUE THREAD

**Issue by nemofq** [gshang2017/docker#167]
偶尔正常，大部分时间会灰屏（重启 Docker/刷新页面无效），求帮助。

PS：加载时会出现正常页面但马上变灰屏
![截屏2022-12-12 14 21 51](https://user-images.githubusercontent.com/5635994/206975428-b1adf4fd-0bbf-4539-b148-bda4ceccbfaf.png)

**Comment by gshang2017** [comment]
有没有可能是屏蔽广告的软件误杀。

**Comment by nemofq** [comment]
@gshang2017 路由器上倒是没开任何屏蔽广告的插件

**Comment by nemofq** [comment]
@gshang2017 我试试给 docker 分配独立 ip，然后设置不过科学，排除下

**Comment by nemofq** [comment]
@gshang2017 测试了下，无效果；因为表现是先加载出了正常页面（能看到一瞬间）然后变灰的，所以感觉应该不是网络的问题

**Comment by gshang2017** [comment]
的确有这个问题。应该是百度网盘的问题。你可以试试旧版本。

**Comment by nemofq** [comment]
@gshang2017 最近几个版本似乎都有这个问题，反正凑合也能用。感谢耐心解答
