### ISSUE TITLE
获取到封面颜色偏暗

### ISSUE THREAD

**Issue by shanyan-wcx** [gshang2017/docker#180]
![屏幕截图 2023-03-05 153004](https://user-images.githubusercontent.com/58252651/222947767-979772c1-6f91-4aa0-a410-931251bc3e86.png)
![屏幕截图 2023-03-05 153020](https://user-images.githubusercontent.com/58252651/222947769-f662762e-d959-41c1-b0fc-87dd2c113fa4.png)

**Comment by Stanleywsy** [comment]
不管是获取的还是自己上传的，好像都会再处理一下，变得暗很多。

**Comment by conghuang** [comment]
同样遇到这个问题

**Comment by zeroL-C** [comment]
我也一样

**Comment by zeroL-C** [comment]
请问楼主解决没有？

**Comment by shanyan-wcx** [comment]
> 请问楼主解决没有？

没解决，只能手动去目录里换图片

**Comment by ygw57** [comment]
一样的问题，尴尬

**Comment by conghuang** [comment]
同样的问题，希望作者能协助诊断一下，非常感谢

**Comment by conghuang** [comment]
问题在新发布的6.21中依然存在，我想知道作者的环境是否正常？ 
谢谢！

**Comment by gshang2017** [comment]
应该是cps/helper.py里save_cover转换了图片的色彩空间 imgc.transform_colorspace("rgb")

你可以卸载 wand或者删掉imgc.transform_colorspace("rgb")或者修改为 imgc.transform_colorspace("srgb")

sed -i s/rgb/srgb/g  /usr/local/calibre-web/app/cps/helper.py

**Comment by gshang2017** [comment]
新版增加了环境变量ENABLE_FIX_COVER_COLOR=true 设定修复封面颜色偏暗。
