### ISSUE TITLE
calibre执行calibredb命令时提示编码错误

### ISSUE THREAD

**Issue by rainsuns** [gshang2017/docker#19]
RT，参考这个https://blog.csdn.net/ningyingqi/article/details/81557944
查了下语言包群晖是支持的，说是要修改dockerFile，大佬看下怎么弄。

docker执行：
--------------------------------------------------
bash-5.0# calibredb add ~/config/upload/* --library-path ~/library              
Python function terminated unexpectedly::'ascii' codec can't encode characters i
n position 0-4: ordinal not in range(128)                                       
Traceback (most recent call last):                                              
  File "site.py", line 83, in main                                              
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordin
al not in range(128)                                                            
bash-5.0#                                                                 

--------------------------------------------------------------
群晖：
root@DSM:~# locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8
root@DSM:~# locale -a
C
cs_CZ.utf8
da_DK.utf8
de_DE.utf8
en_US.utf8
es_ES.utf8
fr_FR.utf8
hu_HU.utf8
it_IT.utf8
ja_JP.utf8
ko_KR.utf8
nb_NO.utf8
nl_NL.utf8
pl_PL.utf8
POSIX
pt_BR.utf8
pt_PT.utf8
ru_RU.utf8
sv_SE.utf8
tr_TR.utf8
zh_CN.utf8
zh_TW.utf8

**Comment by gshang2017** [comment]
在环境变量里加LANG=C.UTF-8或者终端里每次执行export LANG="C.UTF-8"。
用calibredb命令需暂时停掉calibre-server。
停掉：mv /etc/services.d/calibre-server/run /etc/services.d/calibre-server/run.bak 重启容器。
恢复：mv /etc/services.d/calibre-server/run.bak  /etc/services.d/calibre-server/run 重启容器。

**Comment by rainsuns** [comment]
感谢大佬，测试了一下，已经可以用命令批量添加书籍了

========================================
bash-5.0# calibredb add --library-path=/library/ -r /config/upload/                                                                             
/opt/calibre/bin/pdfinfo: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdfinfo)                      
/opt/calibre/bin/pdfinfo: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdfinfo)                      
/opt/calibre/bin/pdfinfo: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/lib/libpoppler.so.66)             
/opt/calibre/bin/pdfinfo: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/lib/libpoppler.so.66)             
/opt/calibre/bin/pdfinfo: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdfinfo)                      
/opt/calibre/bin/pdfinfo: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdfinfo)                      
/opt/calibre/bin/pdfinfo: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/lib/libpoppler.so.66)             
/opt/calibre/bin/pdfinfo: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/lib/libpoppler.so.66)             
/opt/calibre/bin/pdftoppm: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdftoppm)                    
/opt/calibre/bin/pdftoppm: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/bin/pdftoppm)                    
/opt/calibre/bin/pdftoppm: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/lib/libpoppler.so.66)            
/opt/calibre/bin/pdftoppm: /usr/lib/libstdc++.so.6: no version information available (required by /opt/calibre/lib/libpoppler.so.66)            
下列书籍已经存在于数据库，未被添加(参见 --duplicates 选项)：                                                                                    
  从华尔街到长城(如何在中国投资)（精选本）                                                                                                      
    /config/upload/[/[(Mei )] Ma Er Ji Er Deng/Cong Hua Er Jie Dao Chang Cheng (Ru He Zai Zhong Guo Tou Zi )(Jing Xuan Ben ) (2362)/metadata.opf
  小王子 (精排四语版,带精美插图)                                                                                                                
    /config/upload/[/[Fa ] Sheng De Ke Xu Bei Li/Xiao Wang Zi  (Jing Pai Si Yu Ban ,Dai Jing Mei Cha Tu ) (2931)/metadata.opf                   
  魔戒全集                                                                                                                                      
    /config/upload/[/[Ying Guo ]J.R.R.Tuo Er Jin/Mo Jie Quan Ji (2843)/Mo Jie Quan Ji - [Ying Guo ]J.R.R.Tuo Er Jin.mobi                        
已加入的书籍 id: 48, 49, 43, 44, 45, 46, 47                                                                                                     
bash-5.0# ^C

**Comment by rainsuns** [comment]
calibre-server虽然也能批量添加，但好像不支持多级子目录下的书，所有用命令了
