### ISSUE TITLE
autoaddbooks 书籍哪儿去了？

### ISSUE THREAD

**Issue by cquliaoli** [gshang2017/docker#190]
docker 只配置了 /book:/autoaddbooks 映射，library 没映射，docker 把 /book 里面的书籍全部删除，备份到哪儿了？

**Comment by gshang2017** [comment]
如果没映射library会将书籍添加至容器里自动创建的library文件夹。

**Comment by cquliaoli** [comment]
但是我发现 autoaddbooks 内容删除了，但是容器里面的 library 啥也没有，难道是重启容器 library 里面内容清空了？

**Comment by gshang2017** [comment]
calibre-web界面里是否有添加的书籍?如果没有你可以看下容器日志，看是否有添加记录。自动添加图书会添加图书至书库并清空文件夹。

**Comment by cquliaoli** [comment]
web 界面没有添加，看不到任何东西，容器日志里面有记录，所以很奇怪

**Comment by gshang2017** [comment]
如果你重来没有映射library文件夹，那么添加的图书就应该出现在容器内部library文件夹里，除非你添加的图书calibre并不支持被全部删除掉了。你可以用同样配置新建容器，只用一本书测试看是否出现在容器内部library里。
