### ISSUE TITLE
请问Aria2NG web如何https访问，我的aria2已配置https，rpc可以远程连接。

### ISSUE THREAD

**Issue by ryanxia0226** [gshang2017/docker#20]
我现在的环境是路由器 ddns 阿里域名，路由器管理页面已实现https，群晖也可以https访问，就是Aria2NG web不能https，问一下是不是因为容器端口是80的原因，如果是的话，请问容器的端口如何修改，谢谢。
![Snipaste_2020-04-08_13-21-00](https://user-images.githubusercontent.com/42346721/78747572-4bb16f00-799c-11ea-8dbb-80fe2ca39537.png)

**Comment by gshang2017** [comment]
如果用的是群晖里的docker，可以用群晖的反代。
方法：
1.群晖-控制面板-应用程序门户-反代：
来源-协议：https；主机名：你的域名。
启用HSTS，HTTP/2。
目的地-协议：http；主机名：群晖地址，端口：docker Aria2NG web端口。
2.群晖-控制面板-安全性-证书：
添加你阿里域名的证书-配置-修改你反代证书为阿里证书。
3.路由器-端口转发或者群晖-控制面板-外网访问-路由-新增：
将群晖反代来源里的https端口转发出去。

**Comment by ryanxia0226** [comment]
感谢，已经搞定。
