### ISSUE TITLE
aria2的ARIANG_RPC_SECRET_AUTO默认参数建议设置为false

### ISSUE THREAD

**Issue by youland** [gshang2017/docker#202]
ARIANG_RPC_SECRET_AUTO false
如果设置为true，当远程访问aria2下载页面时，会在页面里默认设置为token的值，也就是任何人只要打开aria2页面就可以下载了，有风险。
当ARIANG_RPC_SECRET_AUTO设置为false，任何人打开aria2下载页面，如果不设置token的值，是无法下载的。
我自行测试，设置ARIANG_RPC_SECRET_AUTO ture时，在任何地方打开我的aria2就显示为连接状态。设置ARIANG_RPC_SECRET_AUTO false时，只有自己设置了token的浏览器才能进行下载，否则连不上。
当aria2远程下载暴露在公网时，别人不知道你的token值，也无法操作。
![Snipaste_2023-08-10_10-24-35](https://github.com/gshang2017/docker/assets/3339858/72591d8d-77ab-4ccd-ba69-dab7cf67f9e7)
![Snipaste_2023-08-10_10-26-14](https://github.com/gshang2017/docker/assets/3339858/6f662b9f-37b8-4fb2-8e84-b41402cc1527)

**Comment by gshang2017** [comment]
新版已默认设置为false。
