### ISSUE TITLE
qBittorrent WebUI 输入默认密码，提示“无效的用户名或密码。”

### ISSUE THREAD

**Issue by E78870** [gshang2017/docker#210]
启动命令为：
sudo docker run --name=qbittorrent -e QB_WEBUI_PORT=8989 -e QB_EE_BIN=true -e UID=1000 -e GID=1000 -e UMASK=022 --network host -v /etc/qbittorrent:/config -v /fx8350/Downloads:/Downloads --restart unless-stopped johngong/qbittorrent:latest

输入用户名 admin，密码 adminadmin，提示“无效的用户名或密码。”
检查 config 文件没有 WebUI/password_xxx= 字段，没法恢复恢复默认密码。

**Comment by gshang2017** [comment]
新版的默认密码已经不是adminadmin了，需要到容器日志里去看，里面会有自动生产的初始密码。

**Comment by E78870** [comment]
首先，感谢你的回复。
查阅 qbittorrent 的日志，确实 4.6.1 改了这个，我没发现，是我的问题。
下面我查看了两个地方的日志，都没发现密码，能麻烦看看吗？

输入命令 docker logs qbittorrent 查看日志，得到如下输出：

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/qBittorrent.sh
trackers更新任务已设定。
trackers文件一样,不需要更新。
usermod: no changes
cont-init: info: /etc/cont-init.d/qBittorrent.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun cron (no readiness notification)
services-up: info: copying legacy longrun qBittorrent (no readiness notification)
s6-rc: info: service legacy-services successfully started
WebUI 将在内部准备不久后启动。请稍等…`

我猜测密码应该输出于
'WebUI 将在内部准备不久后启动。请稍等…'
的后面？

不过实际会一直卡在这里，但实际通过浏览器访问 WebUI ，它已经正常启动。

另外，输入 journalctl -u docker，输出：
[journalctl -u docker.txt](https://github.com/gshang2017/docker/files/13465937/journalctl.-u.docker.txt)
这里也没有。

**Comment by gshang2017** [comment]
测试是正常的，启动会出现:
WebUI 将 在 内 部 准 备 不 久 后 启 动 。 请 稍 等 …

******** 信 息  ********
要 控 制  qBittorrent， 请 访 问 下 列 地 址 的  WebUI： http://localhost:8989

WebUI 管 理 员 用 户 名 是 ： admin
未 设 置  WebUI 管 理 员 密 码 。 为 此 会 话 提 供 了 一 个 临 时 密 码 ： 

如果一直无法出现，你可以下载旧版设置好后再更新。

**Comment by cnzd** [comment]
我的也是，昨天全新安装，日志停留在
 WebUI 将在内部准备不久后启动。请稍等… 
就不动了，无法获取临时密码。
此时重启qbitorrent 后面的日志才出来，但是临时密码是上次的，重启后还是登录不了

**Comment by gshang2017** [comment]
群晖上没问题，好像直接在linux上会有这个问题，我会看一下是什么原因导致的。

**Comment by maoimiao** [comment]
我也是同样情况 期待解决 openwrt docker下安装 登录时 一直提示这个：无效的用户名或密码

**Comment by cnzd** [comment]
最新版已解决，谢谢

**Comment by E78870** [comment]
一直是以为我的使用方式不对，没想到竟然真的是一个问题。

**Comment by yingfeng-i** [comment]
> 测试是正常的，启动会出现: WebUI 将 在 内 部 准 备 不 久 后 启 动 。 请 稍 等 …
> 
> ******** 信 息 ******** 要 控 制 qBittorrent， 请 访 问 下 列 地 址 的 WebUI： http://localhost:8989
> 
> WebUI 管 理 员 用 户 名 是 ： admin 未 设 置 WebUI 管 理 员 密 码 。 为 此 会 话 提 供 了 一 个 临 时 密 码 ：
> 
> 如果一直无法出现，你可以下载旧版设置好后再更新。

按照这个去日志那边查看，使用这个密码提交后还是回到登录页面。
后面换了个浏览器正常，经测试对firefox兼容性有问题，firefox输入了正确的密码也还是会回到登录页面

**Comment by yingfeng-i** [comment]
> > 测试是正常的，启动会出现: WebUI 将 在 内 部 准 备 不 久 后 启 动 。 请 稍 等 …
> > ******** 信 息 ******** 要 控 制 qBittorrent， 请 访 问 下 列 地 址 的 WebUI： http://localhost:8989
> > WebUI 管 理 员 用 户 名 是 ： admin 未 设 置 WebUI 管 理 员 密 码 。 为 此 会 话 提 供 了 一 个 临 时 密 码 ：
> > 如果一直无法出现，你可以下载旧版设置好后再更新。
> 
> 按照这个去日志那边查看，使用这个密码提交后还是回到登录页面。 后面换了个浏览器正常，经测试对firefox兼容性有问题，firefox输入了正确的密码也还是会回到登录页面

我去，见鬼 ......
页面关掉历史点开又进去了
