### ISSUE TITLE
web端口下账号密码不对，但同样的密码server端口那边就是好的

### ISSUE THREAD

**Issue by wbhinspector** [gshang2017/docker#212]
docker部署的最新版，应该就是6.21版。按配置设置了账号，密码
但在端口8083那边访问，说密码，账号不对。
在8080那个端口访问就可以正常登录，图书什么也没问题，这是怎么回事呀。
我是部署在unraid下的。看了calibre-server下的那个数据库文件里server-users.sqlite账号密码都是对的呀。

**Comment by gshang2017** [comment]
-p 8083:8083	calibre-web web访问端口,默认用户名: admin 默认密码: admin123

**Comment by wbhinspector** [comment]
> -p 8083:8083 calibre-web web访问端口,默认用户名: admin 默认密码: admin123

谢谢大佬的这个docker和及时回复。终于解决了我这个折腾很久的问题了。。
