### ISSUE TITLE
qb: checking permission so long when Download is extremely big

### ISSUE THREAD

**Issue by ElonH** [gshang2017/docker#215]
Download 文件夹内部文件数目过多，检查时间实在太长。

可否加入一个环境变量跳过检查

https://github.com/gshang2017/docker/blob/6ac8920e9b3476739b772ed9559f575a81d4ef0e/qBittorrent/root/etc/cont-init.d/qBittorrent.sh#L39-L40

**Comment by gshang2017** [comment]
新增环境变量 ENABLE_CHOWN_DOWNLOADS=false
