### ISSUE TITLE
calibre_web  遇到如下的错误提示，readme 还有issue 没有相关的资料

### ISSUE THREAD

**Issue by Pan06da** [gshang2017/docker#220]
下列书籍已经存在于数据库，未被添加(参见 --“重复” 选项或--“自动合并”选项)：

**Comment by gshang2017** [comment]
重复添加了相同的书籍。

**Comment by Pan06da** [comment]
你好，想了解一下 这个自动合并是什么功能？ 是把名字一样的数据合并为合集么？ 如果是的话这个命令 是在”CALIBREDB_OTHER_OPTION=“ 进行设置么？

**Comment by gshang2017** [comment]
可以添加到CALIBREDB_OTHER_OPTION里，你需要参考calibredb命令行说明。

**Comment by Pan06da** [comment]
感谢您的回复和提示
