### ISSUE TITLE
calibre-server的容器内端口如何修改？

### ISSUE THREAD

**Issue by shanyan-wcx** [gshang2017/docker#222]

**Comment by gshang2017** [comment]
修改容器内/etc/services.d/calibre-server/run 
calibre-server命令行添加 --port  指定端口，同时修改8080映射端口。

**Comment by shanyan-wcx** [comment]
这样下次更新会被覆盖吧，可以加个环境变量吗

**Comment by gshang2017** [comment]
可以，不知道你为什么要改容器内的？

**Comment by shanyan-wcx** [comment]
因为我需要使用host模式，容器太多了，端口有冲突。

**Comment by gshang2017** [comment]
新增加 CALIBRE_SERVER_PORT 环境变量设置calibre-server端口。
