### ISSUE TITLE
通过autoaddbooks文件夹导入的书籍存盘时还是以拼音形式保存的

### ISSUE THREAD

**Issue by indam** [gshang2017/docker#223]
通过监控文件夹导入的书籍还是会被转成拼音保存到硬盘上，需要自己手动在web页面上编辑元数据保存后才会重新把文件保存到中文名的文件夹下，但英文文件夹还是会保留下来，估计是忘记删除了。

我是raspberry pi 4 挂载的ntfs 硬盘，不知会不会是因为这个导致的。

谢谢。

**Comment by gshang2017** [comment]
-e CALIBRE_ASCII_FILENAME=true	(true|false)设定false时calibre支持中文目录

**Comment by indam** [comment]
> -e CALIBRE_ASCII_FILENAME=true (true|false)设定false时calibre支持中文目录

收到，感谢！
