### ISSUE TITLE
calibre-web查看docker logs日志发现一直在报错(Failed to execute binary)

### ISSUE THREAD

**Issue by chenqs000** [gshang2017/docker#224]
镜像拉取的是latest，目前使用上没什么问题，但是查看容器日志就发现一直报这个错误
Failed to execute binary: /opt/calibre/bin/calibre-server with error: No such file or directory
![image](https://github.com/gshang2017/docker/assets/34451009/28399a43-44dd-4fdc-887c-e20a6118cbf3)

我进容器查看发现是有这个文件的。
![image](https://github.com/gshang2017/docker/assets/34451009/2365ceb2-7df5-4bc6-a64c-ef9cb88463ee)

还有一个小问题不知道有没有关联，我打开一本书点击获取元数据后，那个弹窗一直白屏没数据，然后calibre-web就完全卡死了，后面停掉容器重新打开才正常。

**Comment by gshang2017** [comment]
应该是自动添加图书时无法同时运行calibre-server。临时将calibre-server改了名导致的。不影响使用。

获取元数据卡顿，可能是因为默认有多个搜索源，其中大部分是国外的导致的。你可以设置禁用谷歌试试。

-e DISABLE_GOOGLE_SEARCH=true
-e DISABLE_SCHOLAR_SEARCH=true
