### ISSUE TITLE
获取元数据会跳到找不到内容，请更换关键字

### ISSUE THREAD

**Issue by moonking2020** [gshang2017/docker#23]
不知道是不是0.6.7添加了一个COMICVNIC搜刮器的关系，现在一本书第一次获取元数据没问题，但需要修改元数据的时候，会出现搜索的内容先出来，然后就挑出找不到内容，请更换关键字。我装了好几遍都是这样，后来我改装的0.6.6就没这个毛病,大神能看一下吗？

**Comment by moonking2020** [comment]
![image](https://user-images.githubusercontent.com/66074695/83159067-2ccb8f80-a138-11ea-8b9f-8d3c0cf764f8.png)

**Comment by moonking2020** [comment]
我刚才把0.6,6在线更新到0.6.7就又变成这样了，之前0.6.6是好的

**Comment by gshang2017** [comment]
你可以先改回0.6.6版本的搜索。群晖方法如下：
docker-终端机新增-bash：
1. cd /usr/local/calibre-web/cps/static/js/
2. mv get_meta.js  get_meta.js.bak
3. wget  https://raw.githubusercontent.com/janeczku/calibre-web/24d755b12374bb3342e4b45ff3068ca78155e154/cps/static/js/get_meta.js
4. 重启docker

注意：第三步如果网络不好需多次操作直到出现'get_meta.js' saved即可。

**Comment by moonking2020** [comment]
> 你可以先改回0.6.6版本的搜索。群晖方法如下：
> docker-终端机新增-bash：
> 
> 1. cd /usr/local/calibre-web/cps/static/js/
> 2. mv get_meta.js  get_meta.js.bak
> 3. wget  https://raw.githubusercontent.com/janeczku/calibre-web/24d755b12374bb3342e4b45ff3068ca78155e154/cps/static/js/get_meta.js
> 4. 重启docker
> 
> 注意：第三步如果网络不好需多次操作直到出现'get_meta.js' saved即可。

好的，我晚上回去试试看

**Comment by moonking2020** [comment]
好了，可以了，现在修改元数据搜索没问题了。需要更新下证书然后重装APK
apk update
apk add ca-certificates
update-ca-certificates
apk --no-cache add openssl wget

**Comment by moonking2020** [comment]
还有一个问请教下，我选择了元数据，在编辑元数据这个页面封面是有的，但是保存了之后，跳回首页，这本书的封面又变成cover not available了，好像要过很久再去刷新封面才会出来，这个是网络问题造成的嘛？我印象中以前我用的版本是马上就会出来封面的

**Comment by moonking2020** [comment]
<img width="525" alt="Snipaste_2020-05-29_13-52-14" src="https://user-images.githubusercontent.com/66074695/83226033-a3f23980-a1b3-11ea-82ac-9670de626e17.png">

**Comment by gshang2017** [comment]
清浏览器缓存。

**Comment by moonking2020** [comment]
> 清浏览器缓存。

可以了！
