### ISSUE TITLE
AnkiDroid登录AnkiWeb账户时提示-用户名或密码错误

### ISSUE THREAD

**Issue by da1234cao** [gshang2017/docker#234]
# 问题描述

## 搭建anki-sync-server

参考： https://hub.docker.com/r/johngong/anki-sync-server

docker-compose.yml  文件。

```shell
root@vultr /h/d/s/anki# cat docker-compose.yml 
version: "3"

services:
    anki-container:
        image: johngong/anki-sync-server:latest
        container_name: anki-container
        restart: always
        ports:
          - "8080:8080"
        volumes:
          - UID=1000
          - GID=1000
          - /home/da1234cao/software/anki/data:/ankisyncdir
        environment:
          - SYNC_USER1=xxx:xxxx
```

容器启动成功。

```shell
d2ef2a42dd2b   johngong/anki-sync-server:latest   "/init"            6 minutes ago   Up 6 minutes            0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   anki-container
```

## 安装AnkiDroid

1. 在googleplay中下载安装AnkiDroid，版本是2.18.4。
2. 然后设置自定义同步服务器。
3. 然后，选择登录AnkiWeb账户，提示用户名或密码错误。

![anki-version](https://github.com/user-attachments/assets/08748417-7f3b-4f44-99ca-8205663dc1ce)

![anki-err](https://github.com/user-attachments/assets/330e9878-068e-4312-a719-6c1e3a68016a)

## 最后

我仔细查看过用户名和密码，没有输入错误。

1. 是AnkiDroid和当前docker中的anki-server不匹配吗？ 如果是不匹配的话，我该使用哪个版本的AnkiDroid？

2. 还是我服务端必须启用https服务？ 如果是的话，我并不想购买证书？客户端有没有推荐的替代app。

**Comment by gshang2017** [comment]
应该所有版本都支持，版本 2.17.6 是支持http服务器的。最新版本未测试。没看出你配置有什么问题。检查一下服务器地址配置是否错误。或者用命令行布署试试。

**Comment by da1234cao** [comment]
> 应该所有版本都支持，版本 2.17.6 是支持http服务器的。最新版本未测试。没看出你配置有什么问题。检查一下服务器地址配置是否错误。或者用命令行布署试试。

哦，是我的账号名有个地方拼写错了。

吃了饭，回头一眼就瞅见错误了，之前愣是没看出来 🥲 

谢谢你的回复。
