### ISSUE TITLE
ttrss 无法加载rss

### ISSUE THREAD

**Issue by valuex** [gshang2017/docker#237]
通过hugginn 创建的某个网站的rss，ttrss无法加载，同一个链接，FreshRSS却可以加载。

ttrss 的日志里也没有报错信息。如果要提供什么排查信息，也请告知下怎么导出来。谢谢。

![image](https://github.com/user-attachments/assets/575ec018-c2ce-495e-bf1d-7fccf223acc0)

**Comment by gshang2017** [comment]
404说明网页不存在。应该在浏览器确认下是否能正常访问。如果端口非80或443，需配置 TTRSS_ALLOW_PORTS  。
