### ISSUE TITLE
qbittorrent-ee的webUI疑问

### ISSUE THREAD

**Issue by YUUUCC** [gshang2017/docker#252]
1. docker装在nas上，然后我把电脑的局域网IP放到了白名单中，但是有时候打开还是需要输入密码，请问是为什么？
2. 请问这个按钮是干什么的？光标放上去也没有提示
![image](https://github.com/user-attachments/assets/c5e26f25-61fb-4580-9d8f-1adbfe8ccbda)

**Comment by gshang2017** [comment]
网络需用host模式，图标好像是代表可用正则。
