### ISSUE TITLE
arm64v8版qee的下载位置

### ISSUE THREAD

**Issue by SymanConor** [gshang2017/docker#26]
请教大大，斐讯n1+外置硬盘，容器和软件里设置下载目录为/media/disk1，实际却下载到/var/lib/docker/overlay2/119bc9bd032dd1eba4c56f4943a4719bdd627926c36b0c744db88e7e4606ea48/diff/**media/disk1**，是我漏了什么吗？

**Comment by gshang2017** [comment]
默认下载位置是/Downloads，只需将真实目录/media/disk1映射到/Downloads即可
(-v  /media/disk1:/Downloads)。
