### ISSUE TITLE
求问怎么推送kindle

### ISSUE THREAD

**Issue by zhoucheng8023** [gshang2017/docker#27]
已设置好smtp服务器，邮件测试也完成了，但是已入库的文档没有找到推送选项

**Comment by gshang2017** [comment]
配置用户 Send to Kindle邮箱 选项。

**Comment by zhoucheng8023** [comment]
已经配置了send to kindle邮箱，即kindle邮箱，依然没有找到推送的按键

**Comment by gshang2017** [comment]
按钮在每本书的书籍详情页里，配置了 Send to Kindle邮箱  就会出现(并不是每本都有，书籍过大就不会出现)。

**Comment by zhoucheng8023** [comment]
已解决，感谢回复，DOCKER很棒。
