### ISSUE TITLE
百度网盘内存占用

### ISSUE THREAD

**Issue by sun47451685** [gshang2017/docker#29]
是内存泄漏问题吗。。。
下着下着，从开始的400mb内存占用一直到了6g。
虽然给群晖配了8g内存，但这不应该啊。。
重启网盘又要重新删配置文件才进得去，下载进度也会没。。
貌似网盘的版本还是2.0.3？

**Comment by gshang2017** [comment]
1.内存:试一下群晖docker的资源限制。
2.重启群晖网盘不能登陆：只需要删除配置文件夹下baidunetdiskdata.db(下载进度会保留)，重启docker。如果网盘设置闪退需删除帐户文件夹下userConf.db，重启docker。
3.网盘版本是最新版，软件本身问题。
