### ISSUE TITLE
大佬可以做个反吸血的qBittorrent吗？

### ISSUE THREAD

**Issue by 100001000** [gshang2017/docker#3]
自动更新trackers简直不要太爽，如果有可能抽空把反吸血整进去就完美了，看到一堆的xunleiXXX头都是炸的😂。这是我找到的但是不懂怎么合到一起呢：https://github.com/c0re100/qBittorrent-Enhanced-Edition
    感恩~

**Comment by gshang2017** [comment]
qbittorrent:qee_4.1.6.1

**Comment by 100001000** [comment]
哇。太棒了 感恩🙏
