### ISSUE TITLE
安裝後顯示『加載失敗，請重試』

### ISSUE THREAD

**Issue by thematrixdev** [gshang2017/docker#31]
你好，我使用Ubuntu 2004，用以下指令建立容器
docker create --name=baidunetdisk -p 5800:5800 -p 5900:5900 -v ~/bdp:/config -v ~/Downloads:/config/baidunetdiskdownload --restart unless-stopped johngong/baidunetdisk:latest

執行後，到 http://127.0.0.1:5800 ，畫面顯示『加載失敗，請重試』，請問可能是什麼問題呢？

![image](https://user-images.githubusercontent.com/19472561/88245167-b88d1280-ccc8-11ea-87e6-b05180396725.png)

**Comment by thematrixdev** [comment]
> 23/07/2020 02:15:33 Got connection from client 127.0.0.1
23/07/2020 02:15:33   other clients:
23/07/2020 02:15:33 Got 'ws' WebSockets handshake
23/07/2020 02:15:33 Got protocol: binary
23/07/2020 02:15:33   - webSocketsHandshake: using binary/raw encoding
23/07/2020 02:15:33   - WebSockets client version hybi-13
23/07/2020 02:15:33 Disabled X server key autorepeat.
23/07/2020 02:15:33   to force back on run: 'xset r on' (3 times)
23/07/2020 02:15:33 incr accepted_client=11 for 127.0.0.1:42902  sock=10
23/07/2020 02:15:33 Client Protocol Version 3.8
23/07/2020 02:15:33 Protocol version sent 3.8, using 3.8
23/07/2020 02:15:33 rfbProcessClientSecurityType: executing handler for type 1
23/07/2020 02:15:33 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8
23/07/2020 02:15:33 Pixel format for client 127.0.0.1:
23/07/2020 02:15:33   32 bpp, depth 24, little endian
23/07/2020 02:15:33   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
23/07/2020 02:15:33 no translation needed
23/07/2020 02:15:33 Enabling NewFBSize protocol extension for client 127.0.0.1
23/07/2020 02:15:33 Enabling full-color cursor updates for client 127.0.0.1
23/07/2020 02:15:33 Using image quality level 6 for client 127.0.0.1
23/07/2020 02:15:33 Using JPEG subsampling 0, Q79 for client 127.0.0.1
23/07/2020 02:15:33 Using compression level 9 for client 127.0.0.1
23/07/2020 02:15:33 Enabling LastRect protocol extension for client 127.0.0.1
23/07/2020 02:15:33 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)
23/07/2020 02:15:33 Using tight encoding for client 127.0.0.1
23/07/2020 02:15:34 client_set_net: 127.0.0.1  0.0001
(node:1001) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
23/07/2020 02:16:26 got closure, reason 1001
23/07/2020 02:16:26 rfbProcessClientNormalMessage: read: Connection reset by peer
23/07/2020 02:16:26 client_count: 0
23/07/2020 02:16:26 Restored X server key autorepeat to: 1
23/07/2020 02:16:26 Client 127.0.0.1 gone

**Comment by gshang2017** [comment]
应该是网络原因，我在群晖和Ubuntu 1804上有做测试，没发现问题。是否有安装过某些广告过滤软件阻碍了网盘与百度的连接。

**Comment by CJN96** [comment]
好像是卷映射的问题，镜像中 /config 和 /config/baidunetdiskdownload 映射到不同宿主机的目录就会出现这个现象，把 /config 的映射去掉就好了。

**Comment by thematrixdev** [comment]
adblock關掉了，去掉config的影射，也是不行

docker create --name=baidunetdisk -p 5800:5800 -p 5900:5900 -v ~/Downloads:/config/baidunetdiskdownload --restart unless-stopped johngong/baidunetdisk:latest

![image](https://user-images.githubusercontent.com/19472561/88373803-173ab500-cdcb-11ea-8b5e-8858d42d3862.png)

**Comment by thematrixdev** [comment]
不好意思，我在公司不能使用，剛回家試就可以了。但有點奇怪，我在公司是VPN到家中的。。。

**Comment by WoodC2011** [comment]
> 不好意思，我在公司不能使用，剛回家試就可以了。但有點奇怪，我在公司是VPN到家中的。。。

你好，我跟你的情况一样，我怎么即便删了还是不行。。。。
