### ISSUE TITLE
请问下载的镜像怎么看是qb还是qbee

### ISSUE THREAD

**Issue by reov** [gshang2017/docker#32]
看说明有trackers自动更新，但是安装后只看到 ‘自动添加以下 tracker 到新的 torrent’

**Comment by gshang2017** [comment]
看Tags,latest标签只有qb。trackers自动更新是每天直接更新配置文件里的trackers,只要你配置了-自动添加以下 tracker 到新的 torrent-选项,每次添加新的torrent文件就会自动添加最新的trackers。

**Comment by reov** [comment]
> 看Tags,latest标签只有qb。trackers自动更新是每天直接更新配置文件里的trackers,只要你配置了-自动添加以下 tracker 到新的 torrent-选项,每次添加新的torrent文件就会自动添加最新的trackers。

我用的是unraid，从dockerhub下载的，没有群晖那个latest标签

**Comment by gshang2017** [comment]
https://hub.docker.com/r/johngong/qbittorrent/tags
