### ISSUE TITLE
docker创建QTB，网络方式为桥接时无法访问WEBUI，ip+端口提示拒绝访问

### ISSUE THREAD

**Issue by yubanmeiqin9048** [gshang2017/docker#33]

**Comment by gshang2017** [comment]
web访问端口：(默认用户名:admin;默认密码:adminadmin);此端口需与容器端口和环境变量保持一致，否则无法访问。

**Comment by yubanmeiqin9048** [comment]
> web访问端口：(默认用户名:admin;默认密码:adminadmin);此端口需与容器端口和环境变量保持一致，否则无法访问。

我仔细对比过，也重新创建过多次，但是每次访问web就显示拒绝访问（连web都进不去）

**Comment by gshang2017** [comment]
删除配置文件夹和创建的容器。清空浏览器缓存。重试。

**Comment by yubanmeiqin9048** [comment]
> 删除配置文件夹和创建的容器。清空浏览器缓存。重试。

确实是缓存出了问题，请问如何更改默认的BT端口

**Comment by gshang2017** [comment]
默认的BT端口6881改成其它就行(如果要端口一致需一起改掉配置文件端口)。用路由器(手动或开UPnP)转发出去就行。

**Comment by yubanmeiqin9048** [comment]
> 默认的BT端口6881改成其它就行(如果要端口一致需一起改掉配置文件端口)。用路由器(手动或开UPnP)转发出去就行。

在创建容器的时候更改吗？

**Comment by gshang2017** [comment]
是的。映射的端口(-p)需创建容器时更改。

**Comment by yubanmeiqin9048** [comment]
> 是的。映射的端口(-p)需创建容器时更改。

进到WEB里面之后再把web里的那个端口改成创建容器是映射的端口就好了嘛？

**Comment by gshang2017** [comment]
例如改成11111
-p 11111:11111  \
-p 11111:11111/udp  \
配置里监听端口也改成11111。

**Comment by yubanmeiqin9048** [comment]
> 例如改成11111
> -p 11111:11111
> -p 11111:11111/udp
> 配置里监听端口也改成11111。

3q
