### ISSUE TITLE
大佬，可以直接改为docker pull johngong/qbittorrent:qee吗？或者问问，如何升级？

### ISSUE THREAD

**Issue by leonevilred** [gshang2017/docker#34]
rt
大佬辛苦

**Comment by leonevilred** [comment]
或者您的就直接docker pull johngong/qbittorrent:latest就好了

**Comment by gshang2017** [comment]
latest标签目前只有amd64原版，改版qee需含有qee_标签
所有镜像tags可看：https://hub.docker.com/r/johngong/qbittorrent/tags
本地镜像查看： docker images johngong/qbittorrent
命令行升级示例:
qee_4.2.5.11升级到qee_4.2.5.13
1.停止  docker stop qbittorrent(容器名)
2.删除容器  docker rm  qbittorrent
3.删除镜像  docker image rm  johngong/qbittorrent:qee_4.2.5.11（旧镜像）
4.下载镜像  docker pull johngong/qbittorrent:qee_4.2.5.13（升级镜像）
5.创建qbittorrent容器（保持原配置不变）
 docker create  \
    --name=qbittorrent  \
    -e WEBUIPORT=8989  \
    -p 6881:6881  \
    -p 6881:6881/udp  \
    -p 8989:8989  \
    -v /配置文件位置:/config  \
    -v /下载位置:/Downloads  \
    --restart unless-stopped  \
   johngong/qbittorrent:qee_4.2.5.13（升级镜像）
6.运行 docker start qbittorrent

**Comment by leonevilred** [comment]
> latest标签目前只有amd64原版，改版qee需含有qee_标签
> 所有镜像tags可看：https://hub.docker.com/r/johngong/qbittorrent/tags
> 本地镜像查看： docker images johngong/qbittorrent
> 命令行升级示例:
> qee_4.2.5.11升级到qee_4.2.5.13
> 1.停止 docker stop qbittorrent(容器名)
> 2.删除容器 docker rm qbittorrent
> 3.删除镜像 docker image rm johngong/qbittorrent:qee_4.2.5.11（旧镜像）
> 4.下载镜像 docker pull johngong/qbittorrent:qee_4.2.5.13（升级镜像）
> 5.创建qbittorrent容器（保持原配置不变）
> docker create
> --name=qbittorrent
> -e WEBUIPORT=8989
> -p 6881:6881
> -p 6881:6881/udp
> -p 8989:8989
> -v /配置文件位置:/config
> -v /下载位置:/Downloads
> --restart unless-stopped
> johngong/qbittorrent:qee_4.2.5.13（升级镜像）
> 6.运行 docker start qbittorrent

这样子原有的种子文件列表不会清空吗

**Comment by gshang2017** [comment]
配置未变就不会改变。

**Comment by leonevilred** [comment]
> 配置未变就不会改变。

谢谢大佬
