### ISSUE TITLE
calibre-web获取元数据能否添加支持豆瓣读书或者百度吗？

### ISSUE THREAD

**Issue by gzxiexl** [gshang2017/docker#4]
calibre-web获取元数据能否添加支持豆瓣读书或者百度吗？
感谢！！

**Comment by gshang2017** [comment]
建议你用这个docker集成的calibre-server或者桌面版calibre-ebook上传书籍，元数据你可以试下桌面版calibre-ebook修改，它支持豆瓣数据搜索。
