### ISSUE TITLE
新的calibre豆瓣获取元数据失效啦

### ISSUE THREAD

**Issue by molezz** [gshang2017/docker#47]
是我网络问题还是大家的情况？

**Comment by gshang2017** [comment]
calibre-web自带的豆瓣apikey失效了。你可以修改/usr/local/calibre-web/cps/static/js/get_meta.js文件替换成有效的。
目前有效的apikey为054022eaeae0b00e0fc068c0c0a2102a
群晖方法如下：
docker-终端机新增-bash：
sed -i s/0df993c66c0c636e29ecbb5344252a4a/054022eaeae0b00e0fc068c0c0a2102a/g /usr/local/calibre-web/cps/static/js/get_meta.js
重启docker容器。

**Comment by molezz** [comment]
成功了 ，谢谢！
