### ISSUE TITLE
直接点击端口访问不了页面。

### ISSUE THREAD

**Issue by flyhong666** [gshang2017/docker#48]
johngong/qbittorrent:qee-latest
这个从docker 映射出来的端口，点击打开提示：Unauthorized，但是从浏览器打开就可以，希望能修正一下。另外，最新的版本，不要自动开始下载，最大活动数 这些设置不起作用。你再检查一下，谢谢了。

**Comment by gshang2017** [comment]
如果需改端口，web访问端口需与容器端口和环境变量保持一致，否则无法访问。设置不起作用应该是新版自带的问题，需等更新。你可暂时用旧版。

**Comment by flyhong666** [comment]
https://github.com/flyhong666/Test/blob/main/2021-01-02_134732.png
https://github.com/flyhong666/Test/blob/main/2021-01-02_134748.png

**Comment by gshang2017** [comment]
试下关闭选项-WebUI-验证-启用跨站请求伪造 (CSRF) 保护。

**Comment by flyhong666** [comment]
可以了。多谢。
