### ISSUE TITLE
大佬你制作的docker 能不能回撤一下啊？

### ISSUE THREAD

**Issue by flyhong666** [gshang2017/docker#51]
docker pull johngong/qbittorrent:qee-latest  这个的最新版本感觉bug 多，不好用，我更新后，以前的备份删除了。你能不能回撤一下，不采用4.3.2.10。

**Comment by gshang2017** [comment]
docker pull johngong/qbittorrent:qee_4.3.1.11

**Comment by flyhong666** [comment]
> docker pull johngong/qbittorrent:qee_4.3.1.11

还是这个版本舒服，谢谢。。。
