### ISSUE TITLE
日志时间记录为运行时间，可以取到自然时间吗？

### ISSUE THREAD

**Issue by yhl173** [gshang2017/docker#54]
大神 容器日志记录日志时间为容器运行时间，能否支持取到自然时间方便核查问题。

**Comment by gshang2017** [comment]
apk add tzdata 
ln -sf /usr/share/zoneinfo/Asia/Shanghai   /etc/localtime
echo Asia/Shanghai > /etc/timezone
重启容器。

**Comment by yhl173** [comment]
命令执行啦，重启容器之后 日志还是容器运行时间

**Comment by gshang2017** [comment]
这个命令只管容器里面的时间。你可以进容器用date命令看。与群晖docker面板日志选项日志栏里出现的时间一致。如果是旁边的时间栏可能不一样。没改过，不知道如何设置。

**Comment by yhl173** [comment]
好的，感谢大神，我向群晖提工单了，有消息同步

**Comment by yhl173** [comment]
群晖回复：群晖的docker是基于UTC设计的，目前这是一个已知问题，此问题将会于之后的DSM版本中修复 。
