### ISSUE TITLE
calibre-web端文件源数据豆瓣源能否批量匹配

### ISSUE THREAD

**Issue by yhl173** [gshang2017/docker#55]
感谢大神实现文件自动脚本上传功能，极大方便了书库的建立速度，书库建立后面临calibre-web端文件源数据豆瓣源匹配工作，工作量单个点击编辑还是挺大的，能否实现系统脚本批量豆瓣源匹配。

**Comment by gshang2017** [comment]
下的书籍元数据都不标准，不太好处理。

**Comment by yhl173** [comment]
好的，感谢
