### ISSUE TITLE
请问自动添加trackers 对PT下载有影响吗 

### ISSUE THREAD

**Issue by gzxiexl** [gshang2017/docker#6]
请问自动添加trackers 对PT下载有影响吗 ，会不会导致封号。

**Comment by gshang2017** [comment]
不用PT，应该会影响。建议你开两个docker，PT那个去掉自动添加trackers选项。手机上用Transdrone软件去远程管理qbitorrent，挺方便的。

**Comment by gzxiexl** [comment]
> 不用PT，应该会影响。建议你开两个docker，PT那个去掉自动添加trackers选项。手机上用Transdrone软件去远程管理qbittorrent，挺方便的。
