### ISSUE TITLE
大佬请您帮忙做一个arm平台的qbittorrentEE的docker吧

### ISSUE THREAD

**Issue by RoeltaNcRave** [gshang2017/docker#7]
大佬,您好,我通过hub.docker找到您有做支持qbEE版本
我已经找到有人做了arm平台的qbEE了
在这里
https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/53
是有人维护了arm平台的

请打包一个支持arm的qbee的docker吧,每当下载热门资源的时候,一大堆xl开头的吸血客户端,永远百分之0,一直吸血,真的太受不了了

**Comment by gshang2017** [comment]
johngong/qbittorrent:qee_4.1.8.2_arm64v8

**Comment by RoeltaNcRave** [comment]
> johngong/qbittorrent:qee_4.1.8.2_arm64v8

非常的感谢您
已经成功在N1盒子上运行了
再也没有xl开头的吸血鬼了
看着自己的上传流量也终于顺心了,感觉p2p环境又好了一点
再次感谢.
