### ISSUE TITLE
树莓派无法运行calibre-web

### ISSUE THREAD

**Issue by SoraKasvgano** [gshang2017/docker#71]
系统raspbian 64位
 4B
运行方式
`
 docker create  \
    --name=calibre-web  \
   --privileged \
    -p 8083:8083  \
    -v /home/calibre-web:/config  \
    -v /home/wwwroot/233/mnts1:/library  \
    -v /home/wwwroot/233/mnts1/transmissiondownload/complete:/autoaddbooks  \
    -e USER=233  \
    -e PASSWORD=233 \
    --restart unless-stopped  \
    johngong/calibre-web:latest`

报错日志：

rm: can't remove '/root/.config/calibre/global.pyc': No such file or directory,
用户名 admin 已存在
,
输入用户名：: admin
,
你想做什么？ [1-4]: 1
,
3) 移除用户
,
1) 新增用户
,
spawn calibre-server --userdb /srv/calibre/users.sqlite --manage-users
,
2) 编辑已有用户
,
4) 取消
,
[cont-init.d] calibre-web.sh: executing... ,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[fix-attrs.d] applying ownership & permissions fixes...,
[s6-init] ensuring user provided files have correct perms...exited 0.,[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

**Comment by SoraKasvgano** [comment]
补充，自动添加书的功能正常 可以看到目录下 它自己再更新

但是8083 和 8080端口都是拒绝连接

**Comment by SoraKasvgano** [comment]
Failed to execute binary: /opt/calibre/bin/calibre-server with error: No such file or directory,Failed to execute binary: /opt/calibre/bin/calibre-server with error: No such file or directory

**Comment by gshang2017** [comment]
docker create  \
    --name=calibre-web  \
    -p 8083:8083  \
    -p 8080:8080  \
    -e USER=用户名  \
    -e PASSWORD=用户密码 \
    --restart unless-stopped  \
    johngong/calibre-web:latest
用这种配置试下,看能否运行。

**Comment by SoraKasvgano** [comment]
> docker create
> --name=calibre-web
> -p 8083:8083
> -p 8080:8080
> -e USER=用户名
> -e PASSWORD=用户密码
> --restart unless-stopped
> johngong/calibre-web:latest
> 用这种配置试下,看能否运行。

'
Re-enter the new password for admin, to verify: 
,
Enter the new password for admin: 
,
Enter the username: admin
,
What do you want to do? [1-4]: 1
,
User admin added successfully!
,
rm: can't remove '/root/.config/calibre/global.pyc': No such file or directory,
[cont-init.d] calibre-web.sh: exited 0.,
[cont-init.d] done.,
Setting up watches.  Beware: since -r was given, this may take a while!,
[services.d] starting services,
[services.d] done.,
Watches established.,
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root',
calibre server listening on 0.0.0.0:8080,
OPDS feeds advertised via BonJour at: 172.17.0.12 port: 8080'

8083可以访问，http访问8080拒绝连接emmm

**Comment by gshang2017** [comment]
-e USER=用字母配置。

**Comment by SoraKasvgano** [comment]
> -e USER=用字母配置。

对的 是 字母，admin  密码纯数字= =

**Comment by SoraKasvgano** [comment]
·docker create \
--name=calibretest \
-p 8082:8083 \
-p 8081:8080 \
-e USER=admin \
-e PASSWORD=123456 \
--restart unless-stopped \
johngong/calibre-web:latest·

**Comment by SoraKasvgano** [comment]
> -e USER=用字母配置。

emmm救命 8081 起来了 应该是速度慢 刚刚启动

**Comment by gshang2017** [comment]
所有映射文件夹都给777试下,autoaddbooks这个文件夹建议用空文件夹,自动添加书籍后会清空这个文件夹。

**Comment by SoraKasvgano** [comment]
> 所有映射文件夹都给777试下,autoaddbooks这个文件夹建议用空文件夹,自动添加书籍后会清空这个文件夹。

az大佬 终于成了  以前给的是 www的777权限 现在是给的root的777权限emmmm

然后运行命令是 
'docker run -d \
  --name=calibre \
  --privileged \
  -e TZ=Asia/Shanghai \
  -e OAUTHLIB_RELAX_TOKEN_SCOPE=1 \
  -e USER=admin \
  -e PASSWORD=233 \
  -p 8083:8083 \
  -p 8082:8080 \
  -v /home/calibre-web:/config \
  -v /home/wwwroot/1/mnts1/transmissiondownload/complete:/autoaddbooks \
 -v /home/wwwroot/1/mnts1/calibreweb:/library \
  --restart unless-stopped \
johngong/calibre-web:latest'

不过我看后台有个报错 
每次容器重启都有  有点强迫症2333 不过不影响运行。。。。

rm: can't remove '/root/.config/calibre/global.pyc': No such file or directory

**Comment by gshang2017** [comment]
早期版本的calibre-server会产生global.pyc文件。反正不影响使用就没改。

**Comment by SoraKasvgano** [comment]
> 早期版本的calibre-server会产生global.pyc文件。反正不影响使用就没改。

emmm
 好的 谢谢dalao，Dalao的 几个镜像都很好用！ i 了i了！
