### ISSUE TITLE
希望aria2可以自定义trackers地址环境

### ISSUE THREAD

**Issue by abe520** [gshang2017/docker#78]
或者可以用镜像地址https://hub.fastgit.org/ngosang/trackerslist/blob/master/trackers_best_ip.txt
原地址经常404

**Comment by gshang2017** [comment]
会增加环境变量TRACKERS_LIST_URL来设置，等镜像更新后你可以设置为https://raw.fastgit.org/ngosang/trackerslist/master/trackers_best_ip.txt 。
