### ISSUE TITLE
Anki-sync-server 帮助

### ISSUE THREAD

**Issue by i2qbske7kq** [gshang2017/docker#79]
你好。我写这个使用翻译应用程序。如果没道理，我很抱歉。我已经下载并设置 anki 同步服务器到我的覆盆子派。当我去 ip：27701 时，我只看到一个白色页面，上面写着"anki 同步服务器"字样。如何查看闪存卡？谢谢。

**Comment by gshang2017** [comment]
只能同步不同设备之间anki数据，不是AnkiWeb,无法在线查看。 https://github.com/ankicommunity/anki-sync-server
