### ISSUE TITLE
不小心重置了管理员密码

### ISSUE THREAD

**Issue by hprandom** [gshang2017/docker#91]
大神，你好。我不小心重置了管理员admin的密码，现在不知道密码是什么了……  admin123也不对，并且好像没有配置好smtp，所以重置邮件一直没有收到……
请问有没有什么办法解决？谢谢了。

**Comment by gshang2017** [comment]
好像只能重新配置。你可以移除配置文件夹里的app.db重新设置。

**Comment by hprandom** [comment]
app.db删了的话，书籍资料还在吗？

**Comment by gshang2017** [comment]
应该在,你可以先备份一下app.db。

**Comment by hprandom** [comment]
谢谢，也只能如此了。我在NAS中删了半天的app.db，发现什么用都没有，然后才想到要到容器中去删……

**Comment by hprandom** [comment]
遇到了一件很诡异的事情……
我在把共享文件夹中的Docker\Calibre下的app.db文件删掉，一点用都没有……
在容器的Bash中找到了一个app.db，删掉后，原来应当有1000多本书的，只剩下了400多本……
我现在只能用老的app.db，然后登录普通用户继续使用。

**Comment by hprandom** [comment]
……
实我太菜了，才知道可以通过映射的方式把Docker中app.db所在目录映射出来，这样就可以通过修改数据库的方式把密码给改掉了……
已经把原来的app.db中，admin的密码改好了。
