### ISSUE TITLE
calibre-web自动添加书籍的问题

### ISSUE THREAD

**Issue by hprandom** [gshang2017/docker#93]
我在autoaddbooks文件夹中添加了书籍，过会就自动删除了，可是书库里面并没有出现……
这是我哪里没有设置对吗？

**Comment by gshang2017** [comment]
你可以去看容器的运行日志，里面有没添加上的原因。默认设置不会添加已存在于书库的。添加不上的基本是pdf图书。

**Comment by hprandom** [comment]
看了下日志，我知道为什么会没有了。
正常我在calibre-web页面上手动上传的书籍，是放在docker的books目录下的，修改的也是books目录下的metadata.db，
然而，autoaddbooks中的书籍，会自动存放在library目录中，同时也在该目录下的metadata.db中添加了一条书籍信息……
我不知道为什么会这样……然后，能帮忙看一下这个问题是有可能什么原因导致的吗？

**Comment by hprandom** [comment]
我把books映射改回了默认的library，貌似好了……
打扰了😅

**Comment by hprandom** [comment]
…… 自动添加图书的时候，我还打开这桌面的Calibre（两者指向的是同一个数据库），现在数据库坏了，现在新添加的数据不能修改书籍信息了……  
还有救吗？

**Comment by gshang2017** [comment]
你可以试下桌面版calbre的电子书-书库维护，或者用命令行calibredb restore_database重建一下数据库。

**Comment by hprandom** [comment]
估计彻底报废了……  
说桌面上运行，结果显示这个：（Docker中相关容器已经停止运行了）
> Traceback (most recent call last):
  File "calibre\db\restore.py", line 281, in replace_db
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: '\\\\DS1813\\book\\library\\metadata.db' -> '\\\\DS1813\\book\\library\\metadata_pre_restore.db'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
  File "calibre\db\restore.py", line 129, in run
  File "calibre\db\restore.py", line 285, in replace_db
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: '\\\\DS1813\\book\\library\\metadata.db'

在Docker中相关容器的终端机中（Bash）运行命令，显示这个：
> 另一个诸如calibre-server实例的 calibre 程序或主 calibre 程序正在运行。有多个程序可以在同一时间对运行的 calibre 库进行更改是一个坏主意。calibredb可以直接连接到运行的 calibre 内容服务器，通过它进行更改。有关详细信息请参阅--with-library选项的文档。

**Comment by gshang2017** [comment]
容器要完全启动后才可以运行命令。你应该是启动没多久就运行命令才出现这种显示。建议你还是用自动添加书籍重新弄一下。calibredb restore_database这个命令只能重建书籍文件夹里有metadata.opf的。手动上传的书籍没有这个。重建的数据库不会完整。

**Comment by hprandom** [comment]
谢谢回复，我后来在网上找了一个据说可以修复数据库的程序，修补了一下，居然可以了……

**Comment by hprandom** [comment]
现在的问题是：不能自动添加书籍了，每次添加书籍，它都是把我原来存有书籍资料的metadata.db删了，重新建一个空白的……
反正自动添加的书籍我都要手工在编辑一下书籍信息，这个自动添加功能索性不用了。
只能如此了，总比重新一个个添加回来好……
