### ISSUE TITLE
树莓派qee_4.3.9.10版本arm32v7版本登录不了【已解决】

### ISSUE THREAD

**Issue by blurries** [gshang2017/docker#96]
拉取最新的版本qbittorrent:qee-latest 或者qee_4.3.8.10版本，运行成功后登录不了
切换到qee_4.3.1.11 版本可以正常登录

**Comment by gshang2017** [comment]
我用qemu测试了下。可以访问。你检查下环境变量(-e WEBUIPORT=8989)与web访问端口(-p 8989:8989)三个数值是否一致，并清理一下浏览器缓存，再测试一下。

**Comment by blurries** [comment]
> 我用qemu测试了下。可以访问。你检查下环境变量(-e WEBUIPORT=8989)与web访问端口(-p 8989:8989)三个数值是否一致，并清理一下浏览器缓存，再测试一下。

我用树莓派4b不行，不是浏览器缓存问题，你知道日志存放哪里吗，我明天研究下

**Comment by blurries** [comment]
![image](https://user-images.githubusercontent.com/16989791/147253048-4e416828-5264-4f9a-ba0e-09328a1f9abd.png)
docker 日志

**Comment by blurries** [comment]
docker/aria2/root/usr/local/aria2/updatetrackers.sh
curl -so  /tmp/trackers_all.txt $TRACKERS_LIST_URL
貌似环境ssl证书不是最新的 在trackers文件路径是https会下载失败

**Comment by gshang2017** [comment]
你试下这里面的方法https://docs.linuxserver.io/faq#libseccomp。

**Comment by blurries** [comment]
> 你试下这里面的方法[https://docs.linuxserver.io/faq#libseccomp。](https://docs.linuxserver.io/faq#libseccomp%E3%80%82)

大佬NB，可以了👍

**Comment by storybegin** [comment]
> 你试下这里面的方法[https://docs.linuxserver.io/faq#libseccomp。](https://docs.linuxserver.io/faq#libseccomp%E3%80%82)

好使
