### ISSUE TITLE
calibre-web 无法使用 Send to Kindle，报 405 错误

### ISSUE THREAD

**Issue by pix33l** [gshang2017/docker#98]
按照网上找的资料，calibre-web 设置好用户邮箱和 stmp 选项，保存并发送测试邮件，测试通过，邮箱里收到了测试邮件。但是在书籍详情页里面一点 Send to Kindle，就显示 405 错误。

**Comment by gshang2017** [comment]
容器里的web.py文件用成0.6.14的了，我会更新一下，你也可以进容器替换并重启容器 

wget https://raw.githubusercontent.com/janeczku/calibre-web/b564a97cdfc22c0e31e0ae18c6ed2b4320b40e50/cps/web.py -O /usr/local/calibre-web/cps/web.py

**Comment by dubin33** [comment]
> 
嗯嗯，好的，非常感谢能够解答，我试一下。
