### ISSUE TITLE
Downloads目录无法映射 

### ISSUE THREAD

**Issue by Stone-Crown** [gshang2017/docker#99]
你好，我在使用您制作的qbittorrent 镜像

使用以下配置创建并启动实例后发现

config 路径可以成功映射，Downloads 路径一直无法成功映射。

不知哪里出了问题，特此请教。

docker create  \
    --name=qbittorrent  \
    -e WEBUIPORT=8989  \
    -e UID=0  \
    -e GID=0  \
    -e UMASK=022  \
   -p 6881:6881  \
    -p 6881:6881/udp  \
    -p 8989:8989  \
    -v /root:/config  \
    -v /root:/Downloads  \
    --restart unless-stopped  \
    johngong/qbittorrent:latest

玩客云 armbian 环境

**Comment by gshang2017** [comment]
你可以试下在/root下建两个文件夹分别映射，或者换除/root外的其它文件夹。

**Comment by Stone-Crown** [comment]
我有尝试使用/ 或者 /qB 这两个映射，但似乎都无法成功，log里也看不到报错！
